# Generated by Django 5.2.6 on 2025-09-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_add_created_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="welcome_email_sent",
            field=models.BooleanField(default=False),
        ),
    ]
