# Generated by Django 5.2.6 on 2025-09-17 12:25

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_userprofile_avatar_userprofile_bio_userfavourite"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="phone number",
            ),
        ),
    ]
