# Generated by Django 5.2.6 on 2025-09-19 08:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="cache_ttl",
            field=models.IntegerField(default=86400),
        ),
        migrations.AddField(
            model_name="movie",
            name="cached_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="TVShow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("overview", models.TextField(blank=True)),
                ("first_air_date", models.DateField(blank=True, null=True)),
                ("poster_path", models.CharField(blank=True, max_length=255)),
                ("cached_at", models.DateTimeField(auto_now_add=True)),
                ("cache_ttl", models.IntegerField(default=86400)),
                (
                    "genres",
                    models.ManyToManyField(related_name="tvshows", to="movies.genre"),
                ),
            ],
        ),
    ]
