# Generated by Django 5.2.6 on 2025-09-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_genre_movie_cache_ttl_movie_cached_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="overview",
            field=models.TextField(blank=True, null=True),
        ),
    ]
